#!/usr/bin/env node
var completion = require('../lib/completion'),
  exec = require('child_process').exec,
  path = require('path'),
  completer = path.basename(__filename);

var parseTasks = completion.parseTasks,
  parseOut = completion.parseOut,
  log = completion.log;

completion.complete('vagrant', completer, function(err, o) {
  if(err || !o) return;

  exec('vagrant', function(err, stdout, stderr) {
    if(err) return;
    var tasks = parseTasks(stdout, 'vagrant');
    return log(tasks, o);
  });
});

if(completion.isComplete()) return;

console.log([
  'vagrant-complete called outside of a completion context.',
  '» You may want to setup the completion in your ~/.bashrc or ~/.zshrc file, if not already.',
  '',
  '   vagrant-complete completion >> ~/.bashrc',
  'Or',
  '   vagrant-complete completion >> ~/.zshrc'
].join('\n'));

